Repository UTACM/TexasACM.org, pull requests merged in 2019-03, with the labels that each got.

#113 Refactor Main.css
  about.html
  assets/css/about-team.css
  assets/css/calendar.css
  assets/css/corporate.css
  assets/css/dynamic-table.css
  assets/css/elections.css
  assets/css/faq.css
  assets/css/main-dark.css
  assets/css/main.css
  assets/css/tooltip.css
  calendar.html
  corporate.html
  elections.html
  faq.html
  forms.html
  tiny.html
  wishlist.html
Labels: tech debt

#121 Airplane!
  about.html
  images/officer_photos/2018-2019/president-airplane.JPG
Labels: enhancement

#123 Missed a Pres photo link
  about.html
  assets/js/faq.js
  assets/js/forms.js
  assets/js/tiny.js
  assets/js/wishlist.js
  images/officer_photos/2018-2019/president-airplane.jpg
Labels: bug

#126 Remove Duplication of "Upcoming Events" label
  index.html
Labels: enhancement

#134 Santiago dev3
  assets/js/elections.js
  elections.html
Labels: Priority, content
